name: tests
on: workflow_dispatch

permissions:
  pages: write
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pytest --alluredir=allure-results
        continue-on-error: true
      - uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
      - uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
      - id: deploy
        uses: actions/deploy-pages@v4
      - run: |
          echo "### Allure Report" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deploy.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY